2024-02-19 01:14:40,289 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-02-19 01:14:40,971 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['184', 'Sector-51, Gurugram, India', Timestamp('2024-02-19 06:00:00')]
2024-02-19 01:14:40,971 - __main__ - INFO - The hourly data has been written to data/cron_job_data/sector_51_cron_output.csv with Timestamp: 2024-02-19 06:00:00
2024-02-19 01:14:41,641 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['184', 'Sector-51, Gurugram, India', Timestamp('2024-02-19 06:00:00')]
2024-02-19 01:14:41,641 - __main__ - INFO - The hourly data has been written to static/data/sector_51_cron_output.csv with Timestamp: 2024-02-19 06:00:00
2024-02-19 01:14:42,316 - __main__ - INFO - station=> Teri Gram, result => ['156', 'Teri Gram, Gurugram, India', Timestamp('2024-02-19 06:00:00')]
2024-02-19 01:14:42,316 - __main__ - INFO - The hourly data has been written to data/cron_job_data/teri_gram_cron_output.csv with Timestamp: 2024-02-19 06:00:00
2024-02-19 01:14:42,996 - __main__ - INFO - station=> Vikas Sadan, result => ['91', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-02-19 06:00:00')]
2024-02-19 01:14:42,998 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-02-19 06:00:00
2024-02-19 01:14:42,999 - __main__ - INFO - Calling writeData & retrain_model functions.
2024-02-19 01:14:43,005 - __main__ - INFO - df_api columns Index(['AQI'], dtype='object')
2024-02-19 01:14:43,006 - __main__ - INFO - today=> 2024-02-19 & yesterday=> 2024-02-18
2024-02-19 01:14:43,008 - __main__ - INFO - temp_daily_aqi columns Index(['Unnamed: 0', 'Date', 'AQI'], dtype='object')
2024-02-19 01:14:43,010 - __main__ - INFO - temp_daily_aqi[2024-02-18]=> Empty DataFrame
Columns: [Unnamed: 0, AQI]
Index: []
2024-02-19 01:14:43,010 - __main__ - INFO - Index => 1445, yesterday => 2024-02-18 & AQI => 190.0
2024-02-19 01:14:43,011 - __main__ - INFO - Daily AQI data has been written to data/cleaned_data/Forecasting_time_series/sector_51_daily_aqi.csv
2024-02-19 01:14:43,011 - __main__ - INFO - Index => 1445, yesterday => 2024-02-18 & AQI => 190.0
2024-02-19 01:14:43,011 - __main__ - INFO - Daily AQI data has been written to static/data/sector_51_daily_aqi.csv
2024-02-19 01:14:43,015 - __main__ - INFO - Re-training the model & train_end is 2024-02-13 00:00:00
2024-02-19 01:14:44,256 - __main__ - INFO - Retrained the model & MAPE is 48.51%
2024-02-19 01:14:44,257 - __main__ - INFO - Retrained the model & MAE is 98.46925194961759%
2024-02-19 01:14:45,573 - __main__ - INFO - Forecast=> 2024-02-19    203.201936
2024-02-20    206.971275
2024-02-21    205.536327
2024-02-22    210.756568
2024-02-23    219.660124
Freq: D, Name: predicted_mean, dtype: float64
2024-02-19 01:14:45,574 - __main__ - INFO - The forecast data has been written to data/cleaned_data/Forecasting_time_series/forecast_sector_51_daily_aqi.csv
2024-02-19 01:14:45,574 - __main__ - INFO - The forecast data has been written to static/data/forecast_sector_51_daily_aqi.csv
2024-02-19 04:20:51,387 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-02-19 04:20:52,037 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['186', 'Sector-51, Gurugram, India', Timestamp('2024-02-19 09:00:00')]
2024-02-19 04:20:52,037 - __main__ - INFO - The hourly data has been written to data/cron_job_data/sector_51_cron_output.csv with Timestamp: 2024-02-19 09:00:00
2024-02-19 04:20:52,681 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['186', 'Sector-51, Gurugram, India', Timestamp('2024-02-19 09:00:00')]
2024-02-19 04:20:52,681 - __main__ - INFO - The hourly data has been written to static/data/sector_51_cron_output.csv with Timestamp: 2024-02-19 09:00:00
2024-02-19 04:20:53,330 - __main__ - INFO - station=> Teri Gram, result => ['157', 'Teri Gram, Gurugram, India', Timestamp('2024-02-19 09:00:00')]
2024-02-19 04:20:53,330 - __main__ - INFO - The hourly data has been written to data/cron_job_data/teri_gram_cron_output.csv with Timestamp: 2024-02-19 09:00:00
2024-02-19 04:20:53,963 - __main__ - INFO - station=> Vikas Sadan, result => ['109', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-02-19 09:00:00')]
2024-02-19 04:20:53,963 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-02-19 09:00:00
2024-02-19 08:22:24,082 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-02-19 08:22:24,727 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['287', 'Sector-51, Gurugram, India', Timestamp('2024-02-19 12:00:00')]
2024-02-19 08:22:24,727 - __main__ - INFO - The hourly data has been written to data/cron_job_data/sector_51_cron_output.csv with Timestamp: 2024-02-19 12:00:00
2024-02-19 08:22:25,366 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['287', 'Sector-51, Gurugram, India', Timestamp('2024-02-19 12:00:00')]
2024-02-19 08:22:25,366 - __main__ - INFO - The hourly data has been written to static/data/sector_51_cron_output.csv with Timestamp: 2024-02-19 12:00:00
2024-02-19 08:22:25,987 - __main__ - INFO - station=> Teri Gram, result => ['205', 'Teri Gram, Gurugram, India', Timestamp('2024-02-19 12:00:00')]
2024-02-19 08:22:25,987 - __main__ - INFO - The hourly data has been written to data/cron_job_data/teri_gram_cron_output.csv with Timestamp: 2024-02-19 12:00:00
2024-02-19 08:22:26,717 - __main__ - INFO - station=> Vikas Sadan, result => ['76', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-02-19 12:00:00')]
2024-02-19 08:22:26,717 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-02-19 12:00:00
